### PR TITLE
Update metadata to support puppetlabs-firewall 2.0.0 release

### PR DESCRIPTION
**Pull request by blackknight36**
puppetlabs-firewall 2.0 has been released.

### CODE REVIEW

**Comment by jflorian** [comment]
Did you see any reason why 1.8 thru 1.15 is no longer compatible?  I didn't.

**Comment by blackknight36** [comment]
@jflorian Not really, those versions will still work so I guess you could set the compatibility level to >= 1.8.0.

**Comment by blackknight36** [comment]
I've updated the metadata file to support firewall version 1.8.0 through 2.0.0.

**Comment by jflorian** [comment]
Already done.

**Pull request closed without merging**
